# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Digital Discourse: Exploring the World of Cybersecurity and Technology"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to "Digital Discourse: Exploring the World of Cybersecurity and Technology." 
  This blog delves into the latest trends, insights, and innovations in cybersecurity and technology, 
  making complex topics accessible to both beginners and seasoned professionals. 
  Join us as we explore the digital landscape and stay ahead of the curve
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://exyze.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aidevtechx
github_username:  exYze

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
